name: naver_login_sdk_example
description: "Demonstrates how to use the naver_login_sdk plugin."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  naver_login_sdk:
    path: ../

  flutter_logcat: ^1.2.6

dev_dependencies:
#  integration_test:
#    sdk: flutter
#  flutter_test:
#    sdk: flutter
#  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
